(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.ShopModel=factory();})(typeof globalThis==='undefined'?this:globalThis,function(){
  const production=['Check-In','Tear Down','Repair Plan','Waiting Approval','Waiting on Supplement','Waiting on Parts','Body','Prep','Paint','On Hold','Assembly','Sublet','Detail','QC','Ready for Delivery'];
  const delivery=['Ready for Delivery','Pre-close','Contact Customer / Confirm Payment','Delivery Scheduled','Confirmed Total Loss Waiting for Pickup','Completed Waiting for Payment','Delivered Waiting for Payment','Delivered / Paid'];
  const planning=['Unscheduled','This Week','Next Week','2 Weeks Out','3 Weeks Out','Future / Holding'];
  const stages=[...production,'Scheduled','On the Road','No Show','Delivered','Total Loss'];
  const jobKind=ro=>/^\d{5}$/.test(String(ro||'').trim())?'active':'opportunity';
  const isOnsite=j=>jobKind(j.roNumber)==='active'&&j.onsite===true&&!j.mergedInto&&production.includes(j.currentStage);
  const openOpportunity=j=>jobKind(j.roNumber)==='opportunity'&&!j.mergedInto&&!['No Show','Delivered','Total Loss'].includes(j.currentStage);
  const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n)||0);
  const defaults=()=>({insurance:['Allstate','State Farm','GEICO','Progressive','CSAA','Farmers','Other'],technicians:['Travis','Cesar','Jairo','Doro','Tony'],estimators:['Marc','Mickey','Bubba'],payTypes:['Insurance pay','Customer pay','Self pay','Warranty','Commercial'],locations:['Ceres','Modesto','Commercial','Off-Site','Sublet'],appointmentTypes:['Drop-off','Estimate appointment','Pickup / delivery','Tow-in','Sublet','Calibration','Customer meeting','Internal reminder'],colors:[{name:'Insurance pay',color:'#cfedf2'},{name:'Customer pay',color:'#d8f2da'},{name:'Must go',color:'#fff0a9'},{name:'Problem job',color:'#ffd5db'},{name:'Commercial',color:'#e8dcf7'},{name:'Waiting',color:'#ffe2c2'}],flags:['Parts issue','Supplement pending','Customer update needed','Final QC needed','Detail needed','ADAS / calibration','Sublet','Delivery today','Management attention','Customer contacted','Payment confirmed','Deductible owed','Waiting insurance payment','Storage concern','Total loss pickup','Delivered but unpaid','Paid'],coreRecipients:[]});
  function totals(jobs){return jobs.reduce((t,j)=>({count:t.count+1,value:t.value+Number(j.roAmount||0),body:t.body+Number(j.bodyHours||0),paint:t.paint+Number(j.paintHours||0),total:t.total+Number(j.bodyHours||0)+Number(j.paintHours||0)+Number(j.otherHours||0)}),{count:0,value:0,body:0,paint:0,total:0});}
  function boardPatch(board,destination){if(board==='production'){if(!production.includes(destination))throw Error('Unknown production stage.');return {currentStage:destination,onsite:true};}if(board==='delivery'){if(!delivery.includes(destination))throw Error('Unknown delivery stage.');return {deliveryStage:destination};}if(board==='planning'){if(!planning.includes(destination))throw Error('Unknown planning week.');return {planningBucket:destination};}throw Error('Unknown board.');}
  function sameOpportunity(a,b){const norm=x=>String(x||'').trim().toLowerCase();return jobKind(a.roNumber)==='opportunity'&&jobKind(b.roNumber)==='active'&&Number(a.roAmount)>0&&Number(a.roAmount)===Number(b.roAmount)&&norm(a.customerName)!==''&&norm(a.customerName)===norm(b.customerName)&&norm(a.vehicle)!==''&&norm(a.vehicle)!=='vehicle from ccc'&&norm(a.vehicle)===norm(b.vehicle);}
  return {production,delivery,planning,stages,jobKind,isOnsite,openOpportunity,money,defaults,totals,boardPatch,sameOpportunity};
});
