const workspace={settings:ShopModel.defaults(),revision:0,appointments:[],notifications:[],loaded:false,error:'',calendarMode:'Month',calendarDate:new Date().toLocaleDateString('en-CA'),filters:{},settingsCategory:'insurance',flagDisplay:loadFlagDisplay()};
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
const esc=escapeHtml;
function dateKey(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function shiftDate(day,n){const d=new Date(day+'T12:00:00');d.setDate(d.getDate()+n);return dateKey(d);}
function switchView(id){document.querySelector(`.tab[data-tab="${id}"]`)?.click();}
async function loadWorkspace(){
 const paths=['settings','appointments','notifications'];const results=await Promise.allSettled(paths.map(p=>apiRequest('/workspace/'+p)));workspace.error='';
 results.forEach((r,i)=>{if(r.status==='fulfilled'){if(i===0){workspace.settings=r.value.data;workspace.revision=r.value.revision;workspace.loaded=true;}else workspace[paths[i]]=r.value.map(objToCamel);}else if(i===0)workspace.error='Shared boards could not load. Apply database migration 010 and refresh. '+r.reason.message;});
}
function options(list,current,blank){const normalized=list.map(x=>typeof x==='object'?x.name:x);const extra=current&&!normalized.includes(current)?[current]:[];return (blank!==undefined?`<option value="">${esc(blank)}</option>`:'')+[...extra,...normalized].map(x=>`<option ${x===current?'selected':''} value="${esc(x)}">${esc(x)}</option>`).join('');}
function input(label,name,value='',type='text',extra=''){return `<label>${esc(label)}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;}
function select(label,name,list,value='',blank){return `<label>${esc(label)}<select name="${name}">${options(list,value,blank)}</select></label>`;}
function checks(label,name,list,values=[]){return `<fieldset class="staff-picker"><legend>${esc(label)}</legend>${[...new Set([...list,...values])].map(x=>`<label class="check-label"><input type="checkbox" name="${name}" value="${esc(x)}" ${values.includes(x)?'checked':''}>${esc(x)}</label>`).join('')}</fieldset>`;}
// Restored board-card icons (see the icon mapping in client/shared.js). A flag is rendered as an
// icon badge with the label alongside it by default; workspace.flagDisplay='icons' (toggled per
// browser via localStorage, see toggleFlagDisplay) hides the label text once boards get crowded,
// keeping the accessible name/tooltip either way.
function flagBadge(label){return `<span class="flag-badge" title="${esc(label)}" role="img" aria-label="${esc(label)}">${ShopModel.svgIcon(ShopModel.flagIconName(label),14)}<span class="flag-label">${esc(label)}</span></span>`;}
function flagChecks(label,name,list,values=[]){return `<fieldset class="staff-picker"><legend>${esc(label)}</legend>${[...new Set([...list,...values])].map(x=>`<label class="check-label flag-check-label"><input type="checkbox" name="${name}" value="${esc(x)}" ${values.includes(x)?'checked':''}>${ShopModel.svgIcon(ShopModel.flagIconName(x),14)}${esc(x)}</label>`).join('')}</fieldset>`;}
function loadFlagDisplay(){try{return localStorage.getItem('flagDisplay')==='icons'?'icons':'label';}catch(_){return 'label';}}
function toggleFlagDisplay(){workspace.flagDisplay=workspace.flagDisplay==='icons'?'label':'icons';try{localStorage.setItem('flagDisplay',workspace.flagDisplay);}catch(_){}renderUnified();}
function openDialog(title,html,onSubmit){
 document.getElementById('workspaceDialog')?.remove();const dialog=document.createElement('dialog');dialog.id='workspaceDialog';dialog.className='workspace-dialog';
 dialog.innerHTML=`<form><header><h2>${esc(title)}</h2><button type="button" class="quiet" aria-label="Close" data-close>✕</button></header><div class="dialog-content"><div class="dialog-error" role="alert"></div>${html}</div><footer><button type="button" class="quiet" data-close>Cancel</button><button type="submit">Save changes</button></footer></form>`;
 document.body.append(dialog);dialog.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>dialog.close());dialog.addEventListener('close',()=>dialog.remove());dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();const button=dialog.querySelector('[type=submit]');button.disabled=true;dialog.querySelector('.dialog-error').textContent='';try{await onSubmit(new FormData(e.target),dialog);dialog.close();}catch(err){dialog.querySelector('.dialog-error').textContent=err.message;}finally{button.disabled=false;}};dialog.showModal();return dialog;
}
function initUnified(){
 workspace.calendarDate=dateKey();
 document.getElementById('unifiedPanels').innerHTML=['production','deliveryBoard','planningBoard','calendar','opportunities','workspaceSettings','notifications'].map(id=>`<section class="tab-panel" id="${id}"></section>`).join('');
 document.querySelector('.app-header h1').textContent='Shop workspace';document.querySelector('.app-header p').textContent='Production, people and every job in one place.';
 const metrics=document.querySelector('#dashboard .dashboard-grid');if(metrics)metrics.insertAdjacentHTML('afterbegin',`<div class="metric clickable" data-open-tab="daily" data-set-view="dailyView:scheduled"><span id="metricScheduled">0</span><label>Scheduled arrivals</label></div><div class="metric clickable" data-open-tab="daily" data-set-view="dailyView:onRoad"><span id="metricOnRoad">0</span><label>On the Road</label></div><div class="metric clickable" data-open-tab="opportunities"><span id="metricOpportunities">0</span><label>Open opportunities</label></div><div class="metric clickable" data-open-tab="daily" data-set-view="dailyView:offsite"><span id="metricAwaitingArrival">0</span><label>Confirm arrival</label></div>`);
 document.querySelectorAll('form.card').forEach(form=>{if(form.id==='cccImportForm')return;const wrap=document.createElement('details');wrap.className='editor-drawer';const summary=document.createElement('summary');summary.textContent='Add or edit '+({dailyForm:'job',partsForm:'part',taskForm:'task',qcForm:'QC record',employeeForm:'employee'}[form.id]||'record');form.before(wrap);wrap.append(summary,form);});
 // Existing edit actions reveal the appropriate form without changing their behavior.
 for(const name of ['editDaily','editParts','editTask','editQc','editBooth','editFacility','editAr']){const original=window[name];if(typeof original==='function')window[name]=function(...args){const result=original(...args);document.querySelector('.tab-panel.active .editor-drawer')?.setAttribute('open','');return result;};}
 document.addEventListener('change',e=>{if(e.target.id==='currentStage'&&['Scheduled','On the Road','No Show','Delivered','Total Loss'].includes(e.target.value))document.getElementById('onsite').checked=false;});
}
function renderUnified(){
 if(!document.getElementById('production'))return;
 const jobs=store.get('daily');
 document.getElementById('metricScheduled').textContent=jobs.filter(j=>!j.mergedInto&&j.currentStage==='Scheduled').length;
 document.getElementById('metricOnRoad').textContent=jobs.filter(j=>!j.mergedInto&&j.currentStage==='On the Road').length;
 document.getElementById('metricOpportunities').textContent=jobs.filter(ShopModel.openOpportunity).length;
 document.getElementById('metricAwaitingArrival').textContent=jobs.filter(j=>!j.mergedInto&&ShopModel.jobKind(j.roNumber)==='active'&&!j.onsite&&ShopModel.production.includes(j.currentStage)).length;
 document.getElementById('notificationCount').textContent=workspace.notifications.filter(n=>!n.readAt).length||'';
 for(const b of ['production','delivery','planning'])renderBoard(b);
 renderCalendar();renderOpportunities();renderWorkspaceSettings();renderNotifications();
}
function boardFilter(board,key,value){workspace.filters[board]={...workspace.filters[board],[key]:value};renderBoard(board);}
function renderBoard(board){
 const id={production:'production',delivery:'deliveryBoard',planning:'planningBoard'}[board];const title={production:'Production Board',delivery:'Delivery Board',planning:'Planning Board'}[board];
 const f=workspace.filters[board]||{},s=workspace.settings;
 let jobs=store.get('daily').filter(j=>!j.mergedInto&&(board==='production'?ShopModel.isOnsite(j):board==='delivery'?!!j.deliveryStage:ShopModel.jobKind(j.roNumber)==='active'&&!ShopModel.isOnsite(j)&&!['Delivered','Total Loss','No Show'].includes(j.currentStage)));
 jobs=jobs.filter(j=>{
  if(f.search&&!`${j.roNumber} ${j.customerName} ${j.vehicle}`.toLowerCase().includes(f.search.toLowerCase()))return false;
  if(f.location&&j.location!==f.location||f.insurance&&j.insurance!==f.insurance||f.estimator&&j.estimator!==f.estimator||f.payType&&j.payType!==f.payType||f.partsStatus&&j.partsStatus!==f.partsStatus)return false;
  if(f.technician&&![...(j.bodyTechs||[]),...(j.painters||[]),...(j.supportTechs||[])].includes(f.technician))return false;
  if(f.flag&&!(j.boardFlags||[]).includes(f.flag))return false;
  if(f.due==='today'&&j.targetDeliveryDate!==dateKey()||f.due==='past'&&(!j.targetDeliveryDate||j.targetDeliveryDate>=dateKey()||j.currentStage==='Delivered'))return false;
  if(f.supplement&&j.supplementNeeded!=='Yes')return false;if(f.supplement&&j.supplementApproved==='Yes')return false;
  if(f.commercial&&!j.commercial)return false;
  return true;
 });
 const sort=f.sort||'targetDeliveryDate';jobs.sort((a,b)=>['roAmount','bodyHours','paintHours'].includes(sort)?Number(b[sort]||0)-Number(a[sort]||0):String(a[sort]||'9999').localeCompare(String(b[sort]||'9999'),undefined,{numeric:true}));
 const t=ShopModel.totals(jobs),stages=ShopModel[board],field={production:'currentStage',delivery:'deliveryStage',planning:'planningBucket'}[board];
 const filterSelect=(label,key,list)=>`<select aria-label="${label}" onchange="boardFilter('${board}','${key}',this.value)">${options(list,f[key]||'',label)}</select>`;
 document.getElementById(id).innerHTML=`<div class="section-head heading-row"><div><div class="eyebrow">CONCEPT AUTO BODY</div><h2>${title}</h2><p>${board==='production'?'Onsite vehicles, current stages and the next step.':board==='delivery'?'Customer handoffs, pickup and payment.':'Plan upcoming work by week.'}</p></div><button onclick="openBoardJob()">＋ New job</button></div>${workspace.error?`<p class="workspace-error">${esc(workspace.error)}</p>`:''}<div class="board-summary"><div><small>Vehicles</small><b>${t.count}</b></div><div><small>Repair value</small><b>${ShopModel.money(t.value)}</b></div><div><small>Labor hours</small><b>${t.total.toFixed(1)}</b></div><div><small>Body / paint</small><b>${t.body.toFixed(1)} / ${t.paint.toFixed(1)}</b></div></div>
 <div class="toolbar board-toolbar"><input aria-label="Search ${title}" placeholder="Search RO, customer or vehicle…" value="${esc(f.search||'')}" onchange="boardFilter('${board}','search',this.value)">${filterSelect('All locations','location',s.locations)}${filterSelect('All insurance','insurance',s.insurance)}${filterSelect('All technicians','technician',s.technicians)}<select aria-label="Sort cards" onchange="boardFilter('${board}','sort',this.value)">${[['targetDeliveryDate','Target date'],['roNumber','RO number'],['roAmount','Highest value'],['bodyHours','Body hours'],['paintHours','Paint hours'],['insurance','Insurance'],['estimator','Estimator']].map(([v,l])=>`<option value="${v}" ${sort===v?'selected':''}>Sort: ${l}</option>`).join('')}</select><button class="quiet" onclick="document.getElementById('${board}Filters').open=!document.getElementById('${board}Filters').open">More filters</button><button class="quiet" onclick="workspace.filters['${board}']={};renderBoard('${board}')">Clear filters</button><button class="quiet" aria-pressed="${workspace.flagDisplay==='icons'}" onclick="toggleFlagDisplay()">${workspace.flagDisplay==='icons'?'Icons + labels':'Icons only'}</button></div>
 <details id="${board}Filters" class="board-extra"><summary>Estimator, due date, payment and flags</summary><div class="toolbar">${filterSelect('All estimators','estimator',s.estimators)}${filterSelect('All pay types','payType',s.payTypes)}${filterSelect('All parts statuses','partsStatus',['Not ordered','Ordered','Backordered','Partial','Here'])}${filterSelect('All flags','flag',s.flags)}<select aria-label="Target date filter" onchange="boardFilter('${board}','due',this.value)"><option value="">All dates</option><option value="today" ${f.due==='today'?'selected':''}>Due today</option><option value="past" ${f.due==='past'?'selected':''}>Past due</option></select><label class="check-label"><input type="checkbox" ${f.supplement?'checked':''} onchange="boardFilter('${board}','supplement',this.checked)">Supplement pending</label><label class="check-label"><input type="checkbox" ${f.commercial?'checked':''} onchange="boardFilter('${board}','commercial',this.checked)">Commercial</label></div></details>
 <p class="board-tip">Drag a card to move it. Select a card to edit or move it using the stage field.</p><div class="production-columns">${stages.map(stage=>{const column=jobs.filter(j=>(j[field]||'Unscheduled')===stage),sum=ShopModel.totals(column);return `<section class="production-column" data-destination="${esc(stage)}"><header><h3>${esc(stage)} <span>${column.length}</span></h3><b>${ShopModel.money(sum.value)}</b><small>${sum.total.toFixed(1)}h total · B ${sum.body.toFixed(1)}h · P ${sum.paint.toFixed(1)}h</small></header><div>${column.map(job=>boardCard(job)).join('')||'<p class="column-empty">No vehicles here</p>'}</div></section>`;}).join('')}</div>${board==='production'?'<p class="board-tip">Only five-digit ROs confirmed onsite appear here. Scheduled and On the Road jobs have their own dashboard boxes.</p>':''}`;
 document.querySelectorAll(`#${id} .production-column`).forEach(col=>{col.ondragover=e=>{e.preventDefault();col.classList.add('drag-over');};col.ondragleave=()=>col.classList.remove('drag-over');col.ondrop=async e=>{e.preventDefault();col.classList.remove('drag-over');const jobId=e.dataTransfer.getData('text/plain');try{const job=store.get('daily').find(j=>j.id===jobId);if(!job)throw Error('Choose a vehicle from this board.');await upsert('daily',{id:jobId,...ShopModel.boardPatch(board,col.dataset.destination),expectedUpdatedAt:job.updatedAt,expectedVersion:job.version});}catch(err){showStatus(err.message,true);}};});
 document.querySelectorAll(`#${id} .production-card`).forEach(card=>{card.ondragstart=e=>e.dataTransfer.setData('text/plain',card.dataset.job);});
}
function boardCard(j){
 const techs=[...new Set([...(j.bodyTechs||[]),...(j.painters||[]),...(j.supportTechs||[])])];const color=/^#[0-9a-f]{6}$/i.test(j.cardColor||'')?j.cardColor:'#cfedf2';
 const next=workspace.appointments.filter(a=>a.jobId===j.id&&`${a.appointmentDate}T${a.appointmentTime}`>=`${dateKey()}T${new Date().toTimeString().slice(0,5)}`).sort((a,b)=>(a.appointmentDate+a.appointmentTime).localeCompare(b.appointmentDate+b.appointmentTime))[0];
 const cycle=j.inDate?Math.max(0,Math.floor((new Date((j.actualDeliveredDate||dateKey())+'T12:00:00')-new Date(j.inDate+'T12:00:00'))/86400000)):0;
 return `<button class="production-card" style="background:${color}" draggable="true" data-job="${j.id}" onclick="openBoardJob('${j.id}')"><div class="card-ro"><b>RO #${esc(j.roNumber)}</b><small>CT ${cycle}d</small></div><h3>${esc(j.customerName)}</h3><p>${esc(j.vehicle)}</p><div class="card-insurer">${esc(j.insurance||'Insurance unassigned')}<small>${esc(j.payType||'')}</small></div><strong class="card-value">${ShopModel.money(j.roAmount)}</strong><div class="card-hours">B ${Number(j.bodyHours||0).toFixed(1)}h · P ${Number(j.paintHours||0).toFixed(1)}h · T ${(Number(j.bodyHours||0)+Number(j.paintHours||0)+Number(j.otherHours||0)).toFixed(1)}h</div><div class="card-staff">${ShopModel.svgIcon('Users',12)}${esc(techs.join(' / ')||'Technicians unassigned')}<small>Estimator: ${esc(j.estimator||j.assignedTo||'Unassigned')} · ${ShopModel.svgIcon('MapPin',11)}${esc(j.location||'')}</small></div><div class="card-dates">In ${esc(j.inDate||'—')}<span class="${j.targetDeliveryDate&&j.targetDeliveryDate<dateKey()?'late':''}">Out ${esc(j.pickupDate||j.targetDeliveryDate||'—')}</span></div><small>Parts: ${esc(j.partsStatus||'Not set')} · Supplement: ${j.supplementNeeded==='Yes'?(j.supplementApproved==='Yes'?'Approved':'Pending'):'None'}</small><div class="board-flags ${workspace.flagDisplay==='icons'?'icons-only':''}">${(j.boardFlags||[]).map(f=>flagBadge(f)).join('')}</div>${next?`<div class="card-appointment">${ShopModel.svgIcon('CalendarDays',12)}${esc(next.appointmentDate)} · ${esc(next.appointmentTime.slice(0,5))} · ${esc(next.appointmentType)}</div>`:''}</button>`;
}
function openBoardJob(id){
 const j=store.get('daily').find(x=>x.id===id)||{currentStage:'Check-In',planningBucket:'Unscheduled',location:'Ceres',priority:'Normal'},s=workspace.settings;
 const html=`<div class="form-grid">${input('RO / opportunity number','roNumber',j.roNumber,'text','required')}${input('Customer','customerName',j.customerName,'text','required')}${input('Vehicle','vehicle',j.vehicle,'text','required')}${select('Location','location',s.locations,j.location)}${select('Current stage — shared with Shop Control','currentStage',ShopModel.stages,j.currentStage)}<label class="check-label"><input type="checkbox" name="onsite" ${j.onsite?'checked':''}>Physically onsite</label>${select('Delivery stage','deliveryStage',ShopModel.delivery,j.deliveryStage,'Not on delivery board')}${select('Planning week','planningBucket',ShopModel.planning,j.planningBucket)}${select('Insurance','insurance',s.insurance,j.insurance,'Unassigned')}${select('Pay type','payType',s.payTypes,j.payType,'Unassigned')}${select('Estimator','estimator',s.estimators,j.estimator,'Unassigned')}${input('Repair value ($)','roAmount',j.roAmount||0,'number','min="0" step="0.01"')}${input('Body hours','bodyHours',j.bodyHours||0,'number','min="0" step="0.1"')}${input('Paint hours','paintHours',j.paintHours||0,'number','min="0" step="0.1"')}${input('Other labor hours','otherHours',j.otherHours||0,'number','min="0" step="0.1"')}<label>Card color<select name="cardColor">${s.colors.map(c=>`<option value="${esc(c.color)}" ${c.color===j.cardColor?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label>${input('In date','inDate',j.inDate,'date')}${input('Target out','targetDeliveryDate',j.targetDeliveryDate,'date')}${input('Drop-off date','dropoffDate',j.dropoffDate,'date')}${input('Pickup date','pickupDate',j.pickupDate,'date')}${input('Follow-up date','followUpDate',j.followUpDate,'date')}${select('Parts status','partsStatus',['Not ordered','Ordered','Backordered','Partial','Here'],j.partsStatus,'Not set')}${select('Supplement needed','supplementNeeded',['No','Yes'],j.supplementNeeded||'No')}${select('Supplement approved','supplementApproved',['No','Yes'],j.supplementApproved||'No')}<label class="check-label"><input name="commercial" type="checkbox" ${j.commercial?'checked':''}>Commercial vehicle</label><label class="wide">Follow-up notes<textarea name="followUpNotes">${esc(j.followUpNotes)}</textarea></label><label class="wide">Today’s goal<textarea name="todaysGoal">${esc(j.todaysGoal)}</textarea></label></div>${checks('Body technicians','bodyTechs',s.technicians,j.bodyTechs||[])}${checks('Painters','painters',s.technicians,j.painters||[])}${checks('Prep / assembly / detail','supportTechs',s.technicians,j.supportTechs||[])}${flagChecks('Flags','boardFlags',s.flags,j.boardFlags||[])}${id?`<div class="toolbar"><button type="button" class="quiet" onclick="document.getElementById('workspaceDialog').close();editDaily('${id}')">Open full Shop Control job</button><button type="button" class="quiet" onclick="document.getElementById('workspaceDialog').close();openAppointment(null,'${id}')">Schedule appointment</button></div>`:''}`;
 openDialog(id?'Job · '+j.roNumber:'New job',html,async data=>{const values=Object.fromEntries(data);for(const field of ['bodyTechs','painters','supportTechs','boardFlags'])values[field]=data.getAll(field);values.onsite=data.has('onsite');values.commercial=data.has('commercial');for(const field of ['roAmount','bodyHours','paintHours','otherHours'])values[field]=Number(values[field]||0);if(values.currentStage==='Scheduled'&&ShopModel.jobKind(values.roNumber)!=='active')throw Error('Assign a five-digit RO before marking this job Scheduled.');if(values.onsite&&ShopModel.jobKind(values.roNumber)!=='active')throw Error('Active onsite vehicles need a five-digit RO.');await upsert('daily',{...values,id,expectedUpdatedAt:j.updatedAt,expectedVersion:j.version});});
}
function renderOpportunities(){
 const open=store.get('daily').filter(ShopModel.openOpportunity);document.getElementById('opportunities').innerHTML=`<div class="section-head heading-row"><div><div class="eyebrow">FOLLOW-UP WORKSPACE</div><h2>Opportunities</h2><p>Files without a five-digit RO. Follow up, assign an RO, then schedule arrival.</p></div><button onclick="openBoardJob()">＋ New opportunity</button></div><div class="board-summary"><div><small>Open opportunities</small><b>${open.length}</b></div><div><small>Follow-ups due</small><b>${open.filter(j=>j.followUpDate&&j.followUpDate<=dateKey()).length}</b></div><div><small>Converted / matched</small><b>${store.get('daily').filter(j=>j.mergedInto).length}</b></div></div><div class="table-wrap"><table><thead><tr><th>File</th><th>Customer / vehicle</th><th>Amount</th><th>Stage</th><th>Follow-up</th><th>Notes</th><th>Action</th></tr></thead><tbody>${open.map(j=>`<tr><td>${esc(j.roNumber)}</td><td>${esc(j.customerName)}<small>${esc(j.vehicle)}</small></td><td>${ShopModel.money(j.roAmount)}</td><td>${esc(j.currentStage)}</td><td>${esc(j.followUpDate||'Not set')}</td><td>${esc(j.followUpNotes)}</td><td><button onclick="openBoardJob('${j.id}')">Review / schedule</button></td></tr>`).join('')||'<tr><td colspan="7">No open opportunities.</td></tr>'}</tbody></table></div><p class="board-tip">A unique match on customer, full vehicle description and positive dollar amount links an opportunity to its RO and removes it from this open list. History remains under Daily GO List → All records / history.</p>`;
}
function calendarChange(key,value){workspace[key]=value;renderCalendar();}
function stepCalendar(n){const d=new Date(workspace.calendarDate+'T12:00:00');if(workspace.calendarMode==='Month')workspace.calendarDate=dateKey(new Date(d.getFullYear(),d.getMonth()+n,1));else workspace.calendarDate=shiftDate(workspace.calendarDate,n*(workspace.calendarMode==='Day'?1:7));renderCalendar();}
function renderCalendar(){
 const day=workspace.calendarDate,mode=workspace.calendarMode,d=new Date(day+'T12:00:00'),first=dateKey(new Date(d.getFullYear(),d.getMonth(),1)),start=mode==='Month'?shiftDate(first,-new Date(first+'T12:00:00').getDay()):mode==='Day'?day:shiftDate(day,-d.getDay());
 const dates=Array.from({length:mode==='Month'?42:mode==='Day'?1:7},(_,i)=>shiftDate(start,i));const events=workspace.appointments.filter(a=>(!workspace.calendarLocation||a.location===workspace.calendarLocation)&&(!workspace.calendarType||a.appointmentType===workspace.calendarType)).sort((a,b)=>(a.appointmentDate+a.appointmentTime).localeCompare(b.appointmentDate+b.appointmentTime));
 document.getElementById('calendar').innerHTML=`<div class="section-head heading-row"><div><div class="eyebrow">SHARED SCHEDULE</div><h2>Calendar</h2><p>Appointments linked to the same vehicles as your boards.</p></div><button onclick="openAppointment()">＋ New appointment</button></div><div class="toolbar calendar-controls"><button class="quiet" aria-label="Previous period" onclick="stepCalendar(-1)">‹</button><h3>${esc(d.toLocaleDateString('en-US',{month:'long',year:'numeric',...(mode==='Month'?{}:{day:'numeric'})}))}</h3><button class="quiet" aria-label="Next period" onclick="stepCalendar(1)">›</button><button class="quiet" onclick="calendarChange('calendarDate',dateKey())">Today</button>${['Day','Week','Month','List'].map(x=>`<button class="${mode===x?'':'quiet'}" aria-pressed="${mode===x}" onclick="calendarChange('calendarMode','${x}')">${x}</button>`).join('')}<input type="date" aria-label="Jump to date" value="${day}" onchange="if(this.value)calendarChange('calendarDate',this.value)"><select aria-label="Calendar location" onchange="calendarChange('calendarLocation',this.value)">${options(workspace.settings.locations,workspace.calendarLocation,'All locations')}</select><select aria-label="Appointment type" onchange="calendarChange('calendarType',this.value)">${options(workspace.settings.appointmentTypes,workspace.calendarType,'All appointment types')}</select></div><div class="calendar-scroll"><div class="shared-calendar ${mode.toLowerCase()}">${mode==='Month'?['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=>`<div class="weekday">${x}</div>`).join(''):''}${dates.map(date=>`<section class="calendar-cell ${date===dateKey()?'is-today':''}"><header><b>${new Date(date+'T12:00:00').toLocaleDateString('en-US',mode==='Month'?{day:'numeric'}:{weekday:'short',month:'short',day:'numeric'})}</b><button class="quiet" aria-label="Add appointment on ${date}" onclick="openAppointment(null,null,'${date}')">＋</button></header>${events.filter(a=>a.appointmentDate===date).map(a=>{const j=store.get('daily').find(j=>j.id===a.jobId);return `<button class="appointment-card" onclick="openAppointment('${a.id}')"><b>${esc(a.appointmentTime.slice(0,5))} · ${esc(a.title)}</b><small>${esc(a.appointmentType)} · ${a.duration} min · ${esc(a.location)}</small>${j?`<small>RO ${esc(j.roNumber)} · ${esc(j.customerName)}</small>`:''}</button>`;}).join('')}</section>`).join('')}</div></div><p class="board-tip">Times use the shop’s local clock. List shows the selected week. A drop-off appointment does not mark a vehicle onsite; confirm its arrival in the job.</p>`;
}
function openAppointment(id,jobId,date){
 const a=workspace.appointments.find(x=>x.id===id)||{jobId:jobId||'',appointmentDate:date||dateKey(),appointmentTime:'09:00',duration:30,location:'Ceres',appointmentType:workspace.settings.appointmentTypes[0]},s=workspace.settings;
 const html=`<div class="form-grid">${input('Title','title',a.title,'text','required maxlength="300"')}${select('Type','appointmentType',s.appointmentTypes,a.appointmentType)}${input('Date','appointmentDate',a.appointmentDate,'date','required')}${input('Time','appointmentTime',a.appointmentTime.slice(0,5),'time','required')}${input('Duration (minutes)','duration',a.duration,'number','required min="5" max="1440"')}${select('Location','location',s.locations,a.location)}<label class="wide">Linked vehicle<select name="jobId"><option value="">No linked vehicle</option>${store.get('daily').filter(j=>!j.mergedInto).map(j=>`<option value="${j.id}" ${j.id===a.jobId?'selected':''}>RO ${esc(j.roNumber)} · ${esc(j.customerName)} · ${esc(j.vehicle)}</option>`).join('')}</select></label><label class="wide">Notes<textarea name="notes">${esc(a.notes)}</textarea></label></div>${id?`<button type="button" class="danger" onclick="deleteAppointment('${id}')">Delete appointment</button>`:''}`;
 openDialog(id?'Edit appointment':'New appointment',html,async data=>{const values=Object.fromEntries(data);values.duration=Number(values.duration);const mins=t=>Number(t.slice(0,2))*60+Number(t.slice(3,5));const overlap=workspace.appointments.some(x=>x.id!==id&&x.location===values.location&&x.appointmentDate===values.appointmentDate&&mins(x.appointmentTime)<mins(values.appointmentTime)+values.duration&&mins(values.appointmentTime)<mins(x.appointmentTime)+x.duration);if(overlap&&!confirm('Another appointment overlaps at this location. Save this appointment anyway?'))throw Error('Choose another time or confirm the overlap.');values.expectedUpdatedAt=a.updatedAt;await apiRequest('/workspace/appointments'+(id?'/'+id:''),{method:id?'PUT':'POST',body:JSON.stringify(objToSnake(values))});await loadWorkspace();renderUnified();});
}
async function deleteAppointment(id){if(!confirm('Delete this appointment?'))return;try{await apiRequest('/workspace/appointments/'+id,{method:'DELETE'});document.getElementById('workspaceDialog')?.close();await loadWorkspace();renderUnified();}catch(e){document.querySelector('.dialog-error').textContent=e.message;}}
function renderWorkspaceSettings(){
 const admin=['admin','owner'].includes(currentUser?.role);const labels={insurance:'Insurance companies',technicians:'Technicians',estimators:'Estimators',payTypes:'Pay types',locations:'Locations',appointmentTypes:'Appointment types',colors:'Card colors',flags:'Icons / flags',coreRecipients:'Core alert recipients',missedCallEscalation:'Missed Call Escalation'};const key=workspace.settingsCategory,s=workspace.settings;
 document.getElementById('workspaceSettings').innerHTML=`<div class="section-head"><div class="eyebrow">WORKSPACE SETTINGS</div><h2>Make it work for your shop</h2><p>Shared options for every board and appointment.${admin?'':' An owner or admin can change these settings.'}</p></div>${workspace.error?`<p class="workspace-error">${esc(workspace.error)}</p>`:''}<div class="settings-layout"><nav>${Object.entries(labels).map(([k,l])=>`<button class="${key===k?'':'quiet'}" onclick="workspace.settingsCategory='${k}';renderWorkspaceSettings()">${l}</button>`).join('')}</nav><div class="card"><div class="heading-row"><h3>${labels[key]}</h3>${admin?`<button onclick="editWorkspaceOption('${key}')">＋ Add option</button>`:''}</div>${(s[key]||[]).map((value,i)=>`<div class="setting-row">${key==='colors'?`<span class="color-swatch" style="background:${esc(value.color)}"></span>`:''}${key==='flags'?ShopModel.svgIcon(ShopModel.flagIconName(value),16):''}<span>${esc(key==='colors'?value.name:['coreRecipients','missedCallEscalation'].includes(key)?(employeesCache.find(e=>e.id===value)?.fullName||value):value)}</span>${admin?`<button class="quiet" onclick="editWorkspaceOption('${key}',${i})">Edit</button><button class="quiet" onclick="removeWorkspaceOption('${key}',${i})">Remove</button>`:''}</div>`).join('')}${key==='coreRecipients'?'<p class="board-tip">If none are selected, opted-in office, parts, owner and admin staff receive core alerts. The assigned employee also receives an alert. Inactive employees and employees with notifications disabled are excluded.</p>':key==='missedCallEscalation'?'<p class="board-tip">Everyone listed here gets emailed if a missed call has no logged callback attempt within 1 business hour. If none are selected, overdue calls cannot be escalated and are flagged in the Activity Log instead.</p>':key==='flags'?'<p class="board-tip">Removing an option does not delete existing assignments. Existing values remain visible in records. Icons follow the shop’s standard set above; a custom or renamed flag not in that list uses a plain flag icon.</p>':'<p class="board-tip">Removing an option does not delete existing assignments. Existing values remain visible in records.</p>'}<div class="settings-import"><h3>Bring in the standalone board</h3><p class="board-tip">Import its exported backup. Matching ROs are reviewed before any update; sample records are excluded.</p>${admin?'<input type="file" id="legacyBoardFile" accept=".json,application/json" aria-label="Standalone production board backup"><button onclick="previewLegacyImport()">Review import</button>':''}</div></div></div>`;
}
async function saveWorkspaceSettings(data){const result=await apiRequest('/workspace/settings',{method:'PUT',body:JSON.stringify({data,revision:workspace.revision})});workspace.settings=result.data;workspace.revision=result.revision;renderUnified();}
function editWorkspaceOption(key,index){const old=workspace.settings[key][index];const value=typeof old==='object'?old.name:old||'';let html=input('Name','name',value,'text','required maxlength="120"');if(key==='colors')html+=input('Color','color',old?.color||'#cfedf2','color');if(['coreRecipients','missedCallEscalation'].includes(key))html=`<label>Employee<select name="name" required>${employeesCache.map(e=>`<option value="${e.id}" ${old===e.id?'selected':''}>${esc(e.fullName||e.username)}</option>`).join('')}</select></label>`;openDialog('Edit shared option',html,async form=>{const name=String(form.get('name')).trim();const data=structuredClone(workspace.settings);if(data[key].some((x,i)=>i!==index&&(typeof x==='object'?x.name:x)===name))throw Error('That option already exists.');const next=key==='colors'?{name,color:form.get('color')}:name;if(index===undefined)data[key].push(next);else data[key][index]=next;await saveWorkspaceSettings(data);});}
async function removeWorkspaceOption(key,index){if(!confirm('Remove this option from future selections? Existing records retain their value.'))return;try{const data=structuredClone(workspace.settings);data[key].splice(index,1);await saveWorkspaceSettings(data);}catch(e){showStatus(e.message,true);}}
function renderNotifications(){document.getElementById('notifications').innerHTML=`<div class="section-head"><h2>Your notifications</h2><p>Core-part alerts for your employee account.</p></div>${workspace.notifications.map(n=>`<article class="card notification ${n.readAt?'read':''}"><h3>${esc(n.title)}</h3><p>${esc(n.message)}</p><small>${esc(new Date(n.createdAt).toLocaleString())}</small>${!n.readAt?`<button class="quiet" onclick="readNotification('${n.id}')">Mark read</button>`:''}</article>`).join('')||'<div class="card">No notifications yet.</div>'}`;}
async function readNotification(id){try{await apiRequest('/workspace/notifications/'+id+'/read',{method:'PUT'});await loadWorkspace();renderUnified();}catch(e){showStatus(e.message,true);}}
async function deleteSelectedParts(){const ids=[...selectedPartIds],rows=currentPartsGroupRows();if(!ids.length)return showStatus('Select parts first.',true);if(!currentUser?.canDelete)return showStatus('Your account cannot delete parts.',true);if(!confirm(`Delete ${ids.length} selected parts for RO ${rows[0]?.partsRoNumber}?`))return;try{await apiRequest('/workspace/parts/bulk',{method:'POST',body:JSON.stringify({action:'delete',ids,ro_number:rows[0].partsRoNumber})});cache.parts=(await api.list('parts')).map(objToCamel);const key=currentPartsGroupKey;renderAll();if(cache.parts.some(r=>partGroupKey(r)===key))openPartsGroup(encodeURIComponent(key));else closePartsModal();showStatus(`${ids.length} parts deleted.`);}catch(e){showStatus(e.message,true);}}
function openBulkPartsEditor(){if(!selectedPartIds.size)return showStatus('Select parts first.',true);const fields=[['partStatus','Status',['Need to Order','Ordered','Backordered','Received','Mirror Matched','Wrong Part','Return Needed','Credit Pending','Returned','Complete']],['partVendor','Vendor'],['partAssignedTo','Assigned to'],['partEta','ETA',null,'date'],['partNotes','Notes'],['partMirrorMatched','Mirror matched',['No','Yes']],['partReturnNeeded','Return needed',['No','Yes']],['partCreditNeeded','Credit needed',['No','Yes']],['hasCore','Has a core',['true','false']],['coreReturned','Core returned',['true','false']]];
 const html=`<p>Only checked fields will change on ${selectedPartIds.size} selected parts.</p><div class="form-grid">${fields.map(([key,label,list,type])=>`<div><label class="check-label"><input type="checkbox" name="apply" value="${key}">Change ${label.toLowerCase()}</label>${list?select(label,key,list,list[0]):input(label,key,'',type||'text')}</div>`).join('')}</div>`;
 openDialog('Edit selected parts',html,async form=>{const patch={};for(const key of form.getAll('apply'))patch[key]=['hasCore','coreReturned'].includes(key)?form.get(key)==='true':form.get(key);if(!Object.keys(patch).length)throw Error('Choose at least one field to change.');await apiRequest('/workspace/parts/bulk',{method:'POST',body:JSON.stringify({action:'update',ids:[...selectedPartIds],ro_number:currentPartsGroupRows()[0].partsRoNumber,patch:objToSnake(patch)})});cache.parts=(await api.list('parts')).map(objToCamel);const key=currentPartsGroupKey;renderAll();openPartsGroup(encodeURIComponent(key));});
}
async function previewLegacyImport(){
 try{const file=document.getElementById('legacyBoardFile').files[0];if(!file)throw Error('Choose an exported Production Board backup.');const data=JSON.parse(await file.text());if(data.schemaVersion!==1||!Array.isArray(data.jobs)||!data.settings)throw Error('This is not a Production Board backup.');if(data.demo)throw Error('This backup is marked as a sample workspace. Import real jobs only.');const result=await apiRequest('/workspace/import-board',{method:'POST',body:JSON.stringify({data,dryRun:true})});
 openDialog('Review Production Board import',`<p>${result.create} new jobs, ${result.update} existing ROs to update, ${result.appointments} appointments. Existing job stages and board fields will be updated to the backup values.</p><p>Save changes applies this import in one transaction.</p><p class="board-tip">Make a database backup before importing. Running the same backup again will update linked records without duplicating them.</p>`,async()=>{await apiRequest('/workspace/import-board',{method:'POST',body:JSON.stringify({data,dryRun:false,expectedRevision:result.revision})});await loadAll(false);});
 }catch(e){showStatus(e.message,true);}
}
