const test=require('node:test'),assert=require('node:assert/strict'),Module=require('node:module');
const calls=[];let queryImpl=async()=>({rows:[]});
const db={query:async(sql,args=[])=>{calls.push({sql,args});const nums=[...sql.matchAll(/\$(\d+)/g)].map(m=>Number(m[1]));if(nums.length)assert.equal(Math.max(...nums),args.length,'SQL placeholder count');else assert.equal(args.length,0);return queryImpl(sql,args);},release(){}};
const pool={query:db.query,connect:async()=>db};
const routers=[];
function Router(){const r={routes:[],middleware:[],use(...m){this.middleware.push(...m);}};for(const method of ['get','post','put','delete'])r[method]=function(path,...handlers){this.routes.push({method,path,handlers});};routers.push(r);return r;}
const load=Module._load;
Module._load=function(name,parent,...rest){if(name==='express')return {Router};if(name==='jsonwebtoken')return {verify:()=>({id:'user-1'})};if(/(^|\/)db$/.test(name))return {pool};if(name.endsWith('/taskEmails'))return {sendAssignmentEmail:async()=>{}};return load.call(this,name,parent,...rest);};
const auth=require('../src/middleware/auth');const records=require('../src/routes/records');const workspace=require('../src/routes/workspace');
Module._load=load;
async function invoke(router,method,path,body={},user={role:'office',canDelete:true}){
 const route=router.routes.find(r=>r.method===method&&r.path===path);assert.ok(route,`${method} ${path} exists`);let result;const req={headers:{authorization:'Bearer fake-test-token'},params:{id:'00000000-0000-4000-8000-000000000001'},body,user:{id:'user-1',username:'test',fullName:'Test',...user}};
 const res={statusCode:200,status(n){this.statusCode=n;return this;},json(data){result={status:this.statusCode,data};return this;}};
 const stack=[...router.middleware,...route.handlers];async function run(i){if(i>=stack.length)return;let nextPromise;await stack[i](req,res,()=>nextPromise=run(i+1));if(nextPromise)await nextPromise;}await run(0);return result;
}
const userQuery=(sql,user)=>sql.startsWith('SELECT id,username')?{rows:[{id:'user-1',username:'test',full_name:'Test',active:true,role:user.role,can_delete:user.canDelete}]}:null;
const id='00000000-0000-4000-8000-000000000001';
test('office bulk delete is denied when the current database permission is revoked',async()=>{calls.length=0;queryImpl=async sql=>userQuery(sql,{role:'office',canDelete:false})||{rows:[]};const result=await invoke(workspace,'post','/parts/bulk',{action:'delete',ids:[id],ro_number:'17892'});assert.equal(result.status,403);assert.ok(!calls.some(c=>c.sql.startsWith('DELETE')));});
test('bulk edit changes the full requested set once and commits its audit record',async()=>{calls.length=0;queryImpl=async sql=>userQuery(sql,{role:'office',canDelete:true})||(sql.startsWith('SELECT * FROM parts')?{rows:[{id,parts_ro_number:'17892'}]}:{rows:[]});const result=await invoke(workspace,'post','/parts/bulk',{action:'update',ids:[id],ro_number:'17892',patch:{has_core:true,part_status:'Ordered'}});assert.equal(result.status,200);const update=calls.find(c=>c.sql.startsWith('UPDATE parts'));assert.ok(update);assert.equal((update.sql.match(/has_core=/g)||[]).length,1);assert.ok(calls.some(c=>c.sql.startsWith('INSERT INTO activity_log')));assert.equal(calls.at(-1).sql,'COMMIT');});
test('missing or cross-RO selections roll back before any delete',async()=>{calls.length=0;queryImpl=async sql=>userQuery(sql,{role:'office',canDelete:true})||{rows:[]};const result=await invoke(workspace,'post','/parts/bulk',{action:'delete',ids:[id],ro_number:'wrong'});assert.equal(result.status,400);assert.equal(calls.at(-1).sql,'ROLLBACK');assert.ok(!calls.some(c=>c.sql.startsWith('DELETE')));});
test('failure during audit rolls back the group mutation',async()=>{calls.length=0;queryImpl=async sql=>{if(sql.startsWith('INSERT INTO activity_log'))throw Error('simulated audit failure');return userQuery(sql,{role:'office',canDelete:true})||(sql.startsWith('SELECT * FROM parts')?{rows:[{id}]}:{rows:[]});};const result=await invoke(workspace,'post','/parts/bulk',{action:'delete',ids:[id],ro_number:'17892'});assert.equal(result.status,400);assert.equal(calls.at(-1).sql,'ROLLBACK');assert.ok(!calls.some(c=>c.sql==='COMMIT'));});
test('settings are writable only by an owner or administrator',async()=>{queryImpl=async sql=>userQuery(sql,{role:'office',canDelete:true})||{rows:[]};const result=await invoke(workspace,'put','/settings',{data:{},revision:1});assert.equal(result.status,403);});
test('notification acknowledgement is scoped to the signed-in employee',async()=>{calls.length=0;queryImpl=async sql=>userQuery(sql,{role:'body',canDelete:false})||{rows:[]};await invoke(workspace,'put','/notifications/:id/read');const update=calls.find(c=>c.sql.startsWith('UPDATE employee_notifications'));assert.ok(update.sql.includes('AND user_id=$2'));assert.equal(update.args[1],'user-1');});
test('appointments reject invalid times without a write',async()=>{calls.length=0;queryImpl=async sql=>userQuery(sql,{role:'office',canDelete:true})||{rows:[]};const result=await invoke(workspace,'post','/appointments',{title:'Pickup',appointment_type:'Pickup',location:'Ceres',appointment_date:'2026-09-12',appointment_time:'25:10',duration:30});assert.equal(result.status,400);assert.ok(!calls.some(c=>c.sql.startsWith('INSERT INTO appointments')));});
test('daily updates use parameterized version guards and reject stale editor state',async()=>{
 const app={use(path,r){this[path]=r;}};records.mountRecordRoutes(app);const router=app['/api/daily'];const row={id,current_stage:'Body',version:4,updated_at:new Date('2026-09-10T00:00:00Z'),ro_amount:100};
 calls.length=0;queryImpl=async sql=>userQuery(sql,{role:'office',canDelete:true})||(sql.startsWith('SELECT * FROM daily')?{rows:[row]}:sql.startsWith('UPDATE daily')?{rows:[{...row,current_stage:'Paint',version:5}]}:{rows:[]});
 let result=await invoke(router,'put','/:id',{current_stage:'Paint',expected_version:3});assert.equal(result.status,409);assert.ok(!calls.some(c=>c.sql.startsWith('UPDATE daily')));
 calls.length=0;result=await invoke(router,'put','/:id',{current_stage:'Paint',expected_version:4});assert.equal(result.status,200);const update=calls.find(c=>c.sql.startsWith('UPDATE daily'));assert.ok(update.sql.includes('AND version = $'));assert.equal(update.args.at(-1),4);assert.equal(result.data.current_stage,'Paint');
});
